  const STYLES = [
    ['primary',   'Primary'],
    ['secondary', 'Secondary'],
    ['outline',   'Outline'],
    ['ghost',     'Ghost'],
    ['ghostsec',  'Ghost Secondary'],
  ];
  const SIZES = ['56', '48', '40'];

  /* "56 px" is a single technical token, not prose. Dropped into an RTL panel
     the bidi algorithm puts the number to the right of the unit and it reads
     "px 56". Measured, not assumed: unicode-bidi:isolate and :embed both still
     produced "px 56"; only an isolated LTR run produced "56 px". Scoped to
     measurement values, so it stays an isolated run inside an RTL block rather
     than direction chosen from content. */
  const metric = text => '<span class="metric">' + text + '</span>';

  /* ── Configurations ─────────────────────────────────────────────────────
     Icon presence is what the button IS, not something done to it. Each of
     these authors its own content, so each has one intrinsic width derived
     from exactly what it contains. Nothing is generated by hiding part of
     another: there used to be a single icon+label+icon button with a switch
     that set display:none on its icons, which gave one configuration two
     widths — 145.8px and 89.8px at 56px — and reflowed the row on every
     toggle. "Leading" and "trailing" are DOM order, which the flex row maps
     to reading order, so RTL mirrors without any physical flipping. */
  const ICON = '<iconify-icon icon="lucide:search"></iconify-icon>';

  const CONFIGS = [
    ['text',     'Text only',      label => '<span>' + label + '</span>'],
    ['leading',  'Leading icon',   label => ICON + '<span>' + label + '</span>'],
    ['trailing', 'Trailing icon',  label => '<span>' + label + '</span>' + ICON],
    ['both',     'Leading + trailing', label => ICON + '<span>' + label + '</span>' + ICON],
    ['icononly', 'Icon only',      null],   // a different element: jelly-icon-button
  ];

  /* Every string the page shows comes from T, which each build defines before
     loading this file. Behaviour, measurement and layout are identical in both
     languages, so only the words differ — nothing here is duplicated per build,
     and a fix lands in both at once. */
  const T = window.MINAA_BUTTONS_STRINGS;

  const LABEL = { ltr: 'Button', rtl: 'كابسة' };

  /* One button of a given configuration, variant and size. */
  function button(config, variantCls, size, dir) {
    if (config === 'icononly')
      return '<jelly-icon-button shape="circle" label="' + T.search + '" data-config="icononly" ' +
             'class="' + variantCls + ' s' + size + '">' + ICON + '</jelly-icon-button>';
    const build = CONFIGS.find(c => c[0] === config)[2];
    return '<jelly-button dir="' + dir + '" data-config="' + config + '" ' +
           'class="' + variantCls + ' s' + size + '">' +
           '<span class="jelly-label">' + build(LABEL[dir]) + '</span></jelly-button>';
  }

  /* One specimen: the thing itself, and a caption naming what varies. Sections
     are built from these rather than from a matrix, so each row of examples
     changes exactly one variable and nothing is demonstrated twice. */
  const specimen = (caption, markup, note) =>
    '<figure class="specimen">' + markup +
    '<figcaption>' + caption +
    (note ? '<span class="cap-note">' + note + '</span>' : '') +
    '</figcaption></figure>';

  const fill = (id, html) => { document.getElementById(id).innerHTML = html; };

  /* Each build authors every section in its own direction, and shows the other
     one only in the direction section, where the comparison is the point. */
  const DIR = T.dir;
  const BASE_SIZE = '48';
  const BASE_STYLE = 'primary';

  fill('ex-base', specimen('Button', button('text', BASE_STYLE, BASE_SIZE, DIR),
                           T.baseNote));

  fill('ex-config', CONFIGS.filter(([c]) => c !== 'icononly')
    .map(([config, name]) => specimen(name, button(config, BASE_STYLE, BASE_SIZE, DIR)))
    .join(''));

  fill('ex-icon', SIZES.map(size =>
    specimen(metric(size + ' px'), button('icononly', BASE_STYLE, size, DIR))).join(''));

  fill('ex-appearance', STYLES.map(([cls, name]) =>
    specimen(name, button('leading', cls, BASE_SIZE, DIR))).join(''));

  fill('ex-size', SIZES.map(size =>
    specimen(metric(size + ' px'), button('leading', BASE_STYLE, size, DIR))).join(''));

  /* Groups — the only place buttons sit next to each other, so the only place
     the spacing between them is on show, and the only place the colour
     hierarchy is legible as a hierarchy.

     Per Colour Foundations: Primary 700 carries the key action, and Secondary
     600 is the secondary button — "these labels show hierarchy, not brand
     importance". Red is not a destructive colour here; the system reserves no
     brand hue for destruction, and errors are the semantic Orange 500. */
  fill('ex-group', [
    specimen(T.group.pair,
      '<span class="group">' + button('text', 'primary', BASE_SIZE, DIR) +
      button('text', 'secondary', BASE_SIZE, DIR) + '</span>',
      T.group.pairNote),
    specimen(T.group.quiet,
      '<span class="group">' + button('text', 'primary', BASE_SIZE, DIR) +
      button('text', 'ghost', BASE_SIZE, DIR) + '</span>',
      T.group.quietNote),
    specimen(T.group.withIcon,
      '<span class="group">' + button('leading', 'primary', BASE_SIZE, DIR) +
      button('text', 'outline', BASE_SIZE, DIR) +
      button('icononly', 'ghost', BASE_SIZE, DIR) + '</span>',
      T.group.withIconNote),
  ].join(''));

  fill('ex-states', [
    specimen(T.states.rest,  button('leading', BASE_STYLE, BASE_SIZE, DIR), T.states.restNote),
    specimen(T.states.ghost, button('leading', 'ghost', BASE_SIZE, DIR),    T.states.ghostNote),
    specimen(T.states.icon,  button('icononly', BASE_STYLE, BASE_SIZE, DIR), T.states.iconNote),
  ].join(''));

  /* Both directions, always in the same order, so the two builds show the same
     comparison rather than each flattering its own. */
  fill('ex-dir', [
    specimen(T.dirs.rtl, button('leading', BASE_STYLE, BASE_SIZE, 'rtl'), T.dirs.rtlNote),
    specimen(T.dirs.ltr, button('leading', BASE_STYLE, BASE_SIZE, 'ltr'), T.dirs.ltrNote),
  ].join(''));

  /* ── Feedback ───────────────────────────────────────────────────────────
     Jelly's four tones, each fired by an identical button so the only thing
     that varies is the tone. "error" and "neutral" are not tones — measured,
     both fall back to Info — so the set is exactly these four. */
  const TONES = [
    ['info',    'Info',    T.tones.info.label,    T.tones.info.message],
    ['success', 'Success', T.tones.success.label, T.tones.success.message],
    ['warning', 'Warning', T.tones.warning.label, T.tones.warning.message],
    ['danger',  'Danger',  T.tones.danger.label,  T.tones.danger.message],
  ];

  /* The button carries the tone's own word, not the sentence it will show.
     Full sentences made four buttons of four different widths and then the
     caption repeated them; a short label keeps the row even and leaves the
     caption to say what the toast will actually read. */
  /* Base class is primary only so the button arrives with no stroke; the
     data-tone rules replace its fill and label. Outline would have ringed a
     green button in blue. */
  fill('ex-toast', TONES.map(([, name, , message]) =>
    specimen(name, button('leading', 'primary', BASE_SIZE, DIR), '«' + message + '»')).join(''));

  document.querySelectorAll('#ex-toast jelly-button').forEach((el, i) => {
    const [tone, , label, message] = TONES[i];
    el.dataset.tone = tone;
    el.querySelector('.jelly-label > span').textContent = label;
    el.addEventListener('click', () => jellyToast(message, { tone }));
  });

  /* Counted from the DOM rather than written down, so the figure cannot drift
     away from the page the way the old "90 components" line had. */
  document.getElementById('stat-examples').textContent =
    document.querySelectorAll('jelly-button, jelly-icon-button').length;

  /* ═══════════════════════════════════════════════════════════════════════
     COLOUR DRIVEN BY JELLY'S LIVE DEFORMATION

     Jelly emits no motion events and exposes no progress API, but it repaints
     its blob into <canvas part="jelly"> every frame. Measured during a real
     drag: the alpha count moved 523 -> 586 and the alpha centroid shifted
     204.6 -> 195.8, returning to rest afterwards. The canvas transform never
     changes, so the deformation lives purely in those pixels — which means it
     can be read rather than guessed at.

     So each frame, for the one button being touched:
       intensity  = how far the blob has departed from its resting shape
       lean       = which way its centroid has moved
     and the colour is composited into Jelly's own silhouette with
     `source-in`, so it can only ever appear exactly where the deformed body
     is. Origin is the real contact point; the spread leans with the blob;
     when Jelly springs back, intensity falls and the spread retracts along
     the same path. One response, one source of truth.
     ═════════════════════════════════════════════════════════════════════ */
  const CONTROLS = [...document.querySelectorAll('jelly-button, jelly-icon-button')];
  const clamp01 = v => v < 0 ? 0 : v > 1 ? 1 : v;
  /* Reading the deformation */
  const SAMPLE_STEP   = 6;      // pixel stride when reading the blob
  const AREA_SPAN     = 0.14;   // +14% area ~ full intensity
  const SHIFT_SPAN    = 10;     // 10 canvas px of centroid travel ~ full
  const BASELINE_EASE = 0.08;   // how fast the resting sample re-learns when untouched

  /* Knowing when it has settled */
  const STILL_EPS     = 0.004;  // frame-to-frame movement counted as "not moving"
  const STILL_FRAMES  = 12;     // consecutive still frames before the loop lets go

  /* Drawing the wave */
  const CORE      = 0.88;       // solid share of the wave before it fades; the label
                                // uses the same figure so the two cannot drift
  const LEAN_GAIN = 2;          // how far the origin leans with the body's centroid
  const MIN_BAND  = 12;         // floor for the soft edge on the smallest buttons
  const FALLBACK_ACTIVE = 'rgb(232,65,29)';   // only if --fill-active resolves to nothing

  const setP = (el, p) => {
    const v = clamp01(p);
    el.__p = v;
    el.style.setProperty('--p', v.toFixed(4));
  };

  const jellyCanvas = el => el.shadowRoot && el.shadowRoot.querySelector('canvas');

  /* Reads Jelly's rendered blob: area + centroid, cheaply and only on demand. */
  function readBlob(el) {
    const c = jellyCanvas(el);
    if (!c || !c.width) return null;
    if (!el.__ctx) el.__ctx = c.getContext('2d', { willReadFrequently: true });
    const d = el.__ctx.getImageData(0, 0, c.width, c.height).data;
    let n = 0, sx = 0, sy = 0;
    for (let y = 0; y < c.height; y += SAMPLE_STEP)
      for (let x = 0; x < c.width; x += SAMPLE_STEP) {
        if (d[(y * c.width + x) * 4 + 3] > 16) { n++; sx += x; sy += y; }
      }
    return n ? { n, cx: sx / n, cy: sy / n } : null;
  }

  /* Both layers are canvases stacked on Jelly's own, pixel for pixel. They are
     slotted into .jelly-content, its own stacking context above the jelly
     canvas, so a negative z-index puts them between the body and the label —
     tinting or outlining the blob, never the text.

       reveal (z -1)  the colour, composited inside the silhouette
       ring   (z -2)  the outline variant's stroke, derived from the silhouette

     One factory builds both: they differ only in class and depth, and letting
     them drift apart is what let the ring keep a stale size while the reveal
     stayed correct. */
  const LAYERS = {
    reveal: { className: 'reveal-layer', z: -1, node: '__overlay', ctx: '__octx' },
    ring:   { className: 'ring-layer',   z: -2, node: '__ring',    ctx: '__rctx' },
  };

  function layerFor(el, kind) {
    const spec = LAYERS[kind];
    if (el[spec.node]) return el[spec.node];
    const jc = jellyCanvas(el);
    if (!jc) return null;
    const c = document.createElement('canvas');
    c.className = spec.className;
    c.style.cssText = 'position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);' +
                      'pointer-events:none;z-index:' + spec.z + ';';
    el.appendChild(c);
    el[spec.node] = c;
    el[spec.ctx] = c.getContext('2d');
    syncLayer(c, jc);                 // sole owner of layer geometry
    return c;
  }

  /* ── Outline ────────────────────────────────────────────────────────────
     The outline variant needs a real stroke, and Jelly has no ring API — the
     --jelly-ring properties we were setting are Jelly's focus ring, not a
     border, which is how the outline quietly became a plain cream fill when
     the buttons moved onto Jelly. A CSS border is not an option
     either: it would stay a rigid capsule while the body squashes. So the
     stroke is derived from Jelly's own silhouette every frame — draw the blob
     smeared around a small circle, punch the undisplaced blob back out, and
     what is left is an even rim that deforms with the body exactly. */
  const RING_STEPS = 16;

  /* Our layers are composited 1:1 with Jelly's canvas, so any drift in size
     puts the stroke and the fill in different places. Jelly resizes its canvas
     when the button does — after a webfont swap, a reflow, a container change —
     and a layer created before that keeps the old geometry. This re-syncs on
     every paint, so a layer can never stay stale. Returns true if it changed,
     since assigning width/height also clears the canvas. */
  function syncLayer(c, jc) {
    const jcs = getComputedStyle(jc);
    let changed = false;
    if (c.width !== jc.width || c.height !== jc.height) {
      c.width = jc.width; c.height = jc.height; changed = true;
    }
    if (c.style.width !== jcs.width || c.style.height !== jcs.height) {
      c.style.width = jcs.width; c.style.height = jcs.height; changed = true;
    }
    return changed;
  }

  function paintRing(el) {
    const cs = getComputedStyle(el);
    const colour = cs.getPropertyValue('--stroke').trim();
    const widthCss = parseFloat(cs.getPropertyValue('--stroke-width')) || 0;
    if (!colour || widthCss <= 0) return;
    const jc = jellyCanvas(el), c = layerFor(el, 'ring');
    if (!jc || !c) return;
    syncLayer(c, jc);
    const ctx = el.__rctx;
    const scale = jc.width / parseFloat(getComputedStyle(jc).width);
    const w = widthCss * scale;

    ctx.globalCompositeOperation = 'source-over';
    ctx.clearRect(0, 0, c.width, c.height);
    for (let i = 0; i < RING_STEPS; i++) {
      const a = (i / RING_STEPS) * Math.PI * 2;
      ctx.drawImage(jc, Math.cos(a) * w, Math.sin(a) * w);
    }
    ctx.globalCompositeOperation = 'destination-out';
    ctx.drawImage(jc, 0, 0);
    ctx.globalCompositeOperation = 'source-in';
    ctx.fillStyle = colour;
    ctx.fillRect(0, 0, c.width, c.height);
    ctx.globalCompositeOperation = 'source-over';
  }

  /* The pieces of copy the wave has to repaint. jelly-button wraps them in a
     .jelly-label; jelly-icon-button carries a bare icon instead, which the
     wave used to miss entirely — a red glyph then sat on a fully red fill and
     vanished. Our own canvas layers are children too, so they are excluded. */
  function labelParts(el) {
    const wrapped = el.querySelectorAll('.jelly-label > *');
    if (wrapped.length) return wrapped;
    return el.querySelectorAll(':scope > :not(canvas)');
  }

  /* Wipes the colour and puts the label back to its resting colour. The stroke
     is left alone — it belongs to the resting state, not the interaction. */
  function clearReveal(el) {
    if (el.__octx && el.__overlay) el.__octx.clearRect(0, 0, el.__overlay.width, el.__overlay.height);
    resetLabel(el);
  }

  /* Paints the active colour into Jelly's silhouette, from the contact point. */
  function paint(el, intensity, lean) {
    const jc = jellyCanvas(el), o = layerFor(el, 'reveal');
    if (!jc || !o) return;
    syncLayer(o, jc);
    const ctx = el.__octx;
    ctx.globalCompositeOperation = 'source-over';
    ctx.clearRect(0, 0, o.width, o.height);
    if (intensity <= 0.001 || !el.__contact) { resetLabel(el); return; }

    const scale = jc.width / parseFloat(getComputedStyle(jc).width);   // device px per css px
    // contact point, host coords -> canvas coords
    const hb = el.getBoundingClientRect();
    const jb = jc.getBoundingClientRect();
    let ox = (el.__contact.x - jb.left) * scale;
    let oy = (el.__contact.y - jb.top)  * scale;
    // let the spread lean the way the body is leaning
    ox += lean.x * LEAN_GAIN; oy += lean.y * LEAN_GAIN;

    /* Reach = the distance from this contact point to the furthest corner of
       the button, so intensity 1 means "just covered" wherever you touched and
       intensity 0.5 really is half way. A fixed reach saturated long before 1:
       the canvas diagonal by p≈0.45, the button diagonal by p≈0.5 from centre. */
    const cx = el.__contact.x - hb.left, cy = el.__contact.y - hb.top;
    const reach = Math.hypot(Math.max(cx, hb.width - cx),
                             Math.max(cy, hb.height - cy)) * scale;
    const r = Math.max(1, reach * intensity);

    ctx.drawImage(jc, 0, 0);                     // exact deformed silhouette
    ctx.globalCompositeOperation = 'source-in';  // colour only inside the body
    const g = ctx.createRadialGradient(ox, oy, 0, ox, oy, r);
    const active = activeColour(el);
    g.addColorStop(0, active);
    g.addColorStop(CORE, active);
    g.addColorStop(1, active.replace('rgb(', 'rgba(').replace(')', ',0)'));
    ctx.fillStyle = g;
    ctx.fillRect(0, 0, o.width, o.height);
    ctx.globalCompositeOperation = 'source-over';

    paintLabel(el, hb, cx, cy, reach / scale, intensity);
  }

  /* Repaints each label part as the same wave front passes over it, so the
     text and icons turn where the colour actually arrives rather than fading
     on a separate timer. */
  function paintLabel(el, hb, cx, cy, reachCss, intensity) {
    const parts = labelParts(el);
    if (!parts.length) return;
    const front = reachCss * intensity * CORE;          // same front as the fill
    const band = Math.max(MIN_BAND, reachCss * (1 - CORE));   // same soft edge
    parts.forEach(part => {
      const pb = part.getBoundingClientRect();
      const d = Math.hypot(pb.left + pb.width / 2 - hb.left - cx,
                           pb.top + pb.height / 2 - hb.top - cy);
      part.style.setProperty('--t', clamp01((front - d) / band + 0.5).toFixed(3));
    });
  }

  function resetLabel(el) {
    labelParts(el).forEach(p => p.style.setProperty('--t', '0'));
  }

  /* --fill-active may be any CSS colour, and the canvas needs a concrete rgb()
     to build a gradient from. A throwaway element resolves it. The answer is
     fixed by the variant class, so it is worked out once per button rather
     than on every interaction. */
  function activeColour(el) {
    if (el.__activeColour) return el.__activeColour;
    const v = getComputedStyle(el).getPropertyValue('--fill-active').trim();
    let rgb = FALLBACK_ACTIVE;
    if (v) {
      const probe = document.createElement('span');
      probe.style.cssText = 'position:fixed;left:-9999px;color:' + v;
      document.body.appendChild(probe);
      const resolved = getComputedStyle(probe).color;
      probe.remove();
      if (resolved.startsWith('rgb')) rgb = resolved;
    }
    el.__activeColour = rgb;
    return rgb;
  }

  /* One loop per active button. It follows Jelly rather than leading it, and
     stops on its own once the body has settled back to rest. */
  function track(el) {
    if (el.__tracking) return;
    el.__tracking = true;
    activeColour(el);
    if (!el.__rest) el.__rest = readBlob(el);
    let still = 0, prev = null;
    const step = () => {
      const now = readBlob(el);
      const rest = el.__rest;
      if (!now || !rest) { el.__tracking = false; return; }

      /* While nothing is touching it, ease the baseline toward what we see.
         The baseline is read from a live canvas, so it can be captured
         mid-wobble; without this it stays wrong and the button keeps a
         phantom colour forever. */
      if (!el.__engaged) {
        rest.n  += (now.n  - rest.n)  * BASELINE_EASE;
        rest.cx += (now.cx - rest.cx) * BASELINE_EASE;
        rest.cy += (now.cy - rest.cy) * BASELINE_EASE;
      }

      const dArea = (now.n - rest.n) / rest.n;
      const dx = now.cx - rest.cx, dy = now.cy - rest.cy;
      const shift = Math.hypot(dx, dy);
      const intensity = clamp01(Math.max(dArea / AREA_SPAN, shift / SHIFT_SPAN));

      setP(el, intensity);
      paint(el, intensity, { x: dx, y: dy });
      paintRing(el);                             // the stroke deforms with the body

      /* Stop on frame-to-frame stillness, not on distance from the baseline —
         a bad baseline must never be able to keep the loop alive. */
      const moved = prev
        ? Math.abs(now.n - prev.n) / rest.n + Math.hypot(now.cx - prev.cx, now.cy - prev.cy)
        : Infinity;
      prev = now;
      still = moved < STILL_EPS ? still + 1 : 0;
      if (still > STILL_FRAMES && !el.__engaged) {   // settled and no longer touched
        el.__tracking = false; setP(el, 0); clearReveal(el); return;
      }
      requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  }

  CONTROLS.forEach(el => {
    setP(el, 0);
    const contact = e => { el.__contact = { x: e.clientX, y: e.clientY }; };

    el.addEventListener('pointerenter', e => { el.__engaged = true; contact(e); track(el); });
    el.addEventListener('pointermove',  e => { contact(e); track(el); });
    el.addEventListener('pointerdown',  e => { el.__engaged = true; contact(e); track(el); });
    el.addEventListener('pointerup',    e => { contact(e); });
    ['pointerleave','pointercancel'].forEach(t =>
      el.addEventListener(t, () => { el.__engaged = false; }));   // loop unwinds itself

    // Keyboard has no contact point and no deformation to follow.
    el.addEventListener('focus', () => {
      /* Jelly delegates focus into its shadow button, and that inner element is
         the one that matches :focus-visible — the host never does. Testing the
         host meant this returned on every tab stop and keyboard users saw no
         colour at all. */
      const inner = el.shadowRoot && el.shadowRoot.querySelector('button');
      if (!(inner || el).matches(':focus-visible')) return;
      const b = el.getBoundingClientRect();
      el.__contact = { x: b.left + b.width / 2, y: b.top + b.height / 2 };
      setP(el, 1); paint(el, 1, { x: 0, y: 0 });
    });
    el.addEventListener('blur', () => { setP(el, 0); clearReveal(el); });
  });

  /* On resize the resting shape has changed, so the old baseline would read as
     a permanent deformation and has to go.

     The stroke is repainted here as well as by the observer below. The observer
     watches the layout box, but a change in device pixel ratio rewrites Jelly's
     backing store while the CSS box stays put — measured after a viewport
     switch: our layer held 468x288 against Jelly's 410x252 at an identical
     234px on screen, which would have drawn the stroke at 0.88 scale. */
  addEventListener('resize', () => CONTROLS.forEach(el => {
    el.__rest = null;
    settleRing(el);
  }));

  /* Repaint until Jelly has finished resizing rather than once on the event.
     Painting immediately syncs to the size Jelly is about to abandon, and the
     observer cannot cover it — a device-pixel-ratio change rewrites the
     backing store while the layout box it watches stays identical. So watch
     the backing store directly and stop as soon as it holds still. */
  function settleRing(el) {
    if (el.__settling) return;
    el.__settling = true;
    let stable = 0, frames = 0;
    const step = () => {
      const jc = jellyCanvas(el), c = el.__ring;
      if (!jc || ++frames > 40) { el.__settling = false; return; }
      const matched = c && c.width === jc.width && c.height === jc.height;
      if (!matched) { paintRing(el); stable = 0; } else stable++;
      if (stable >= 3) { el.__settling = false; return; }
      requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  }

  /* At rest nothing is tracking, so the stroke has to be repainted whenever the
     button changes size. Fixed timeouts were not enough: the RTL 40px outline
     settled to its final width after the last one, leaving a stroke drawn at
     the old size sitting 16px off the fill.

     The observer watches Jelly's canvas, not the host. Watching the host fires
     while Jelly still holds its previous canvas size, so the stroke resynced to
     stale dimensions and stayed exactly one resize behind — correct until the
     first reflow, then 42px out. The canvas is what we composite against, so it
     is what to follow. */
  const ringWatch = new ResizeObserver(entries => {
    entries.forEach(e => {
      const host = e.target.__host;
      if (host && !host.__tracking) paintRing(host);
    });
  });
  function restRing(el) {
    const attach = () => {
      const jc = jellyCanvas(el);
      if (!jc) { setTimeout(attach, 100); return; }   // the element may not have upgraded yet
      jc.__host = el;
      ringWatch.observe(jc);
      paintRing(el);
    };
    attach();
  }
  CONTROLS.forEach(restRing);

  /* ── Manual scrubber — forces the spread from each button's centre ─────── */
  const scrub = document.getElementById('scrub');
  const scrubOut = document.getElementById('scrub-out');
  scrub.addEventListener('input', () => {
    const v = parseFloat(scrub.value);
    scrubOut.textContent = v.toFixed(2);
    CONTROLS.forEach(el => {
      const b = el.getBoundingClientRect();
      el.__contact = { x: b.left + b.width / 2, y: b.top + b.height / 2 };
      setP(el, v);
      paint(el, v, { x: 0, y: 0 });
    });
    measureWhenSettled();
  });

  /* ── Live measurement — reads what actually rendered, per size ─────────── */
  const SCALE = new Set([0,2,4,6,8,12,16,20,24,32,40,48,64,80,96]);
  const r1 = n => Math.round(n * 10) / 10;

  /* Reads what each configuration actually rendered, and rebuilds its width
     from the parts that are really in it: padding on both sides, each visible
     icon, and one gap per join. A configuration passes only when the rendered
     width equals that sum — which is the same as saying it carries no spacing
     for content it does not have. Text-only has no icon and no gap in the sum,
     so if it still measured icon-width the reservation would show up here. */
  function measureConfig(host) {
    const inner = host.shadowRoot && host.shadowRoot.querySelector('button');
    if (!inner) return null;
    const ics = getComputedStyle(inner);
    const pad = parseFloat(ics.paddingInlineStart);
    const gap = parseFloat(ics.gap) || 0;

    /* The icon button is not padded to its width — it is square by
       construction, so its expected width is its own height. Reporting a
       padding of 0 here would read as a violation of the 24/20/16 rule when
       the rule simply does not apply to this family. */
    if (host.dataset.config === 'icononly') {
      const box = host.getBoundingClientRect();
      return { square: true, icons: 1, gaps: 0,
               expected: r1(box.height), actual: r1(box.width), h: r1(box.height) };
    }
    const label = host.querySelector('.jelly-label');
    const kids = [...label.children];
    const icons = kids.filter(k => k.tagName === 'ICONIFY-ICON');
    const text = kids.find(k => k.tagName === 'SPAN');
    const iconW = icons.reduce((a, k) => a + k.getBoundingClientRect().width, 0);
    const textW = text ? text.getBoundingClientRect().width : 0;
    const gaps = Math.max(0, kids.length - 1);
    return { pad, gap, icons: icons.length, gaps, text: r1(textW),
             expected: r1(pad * 2 + iconW + gaps * gap + textW),
             actual: r1(host.getBoundingClientRect().width),
             h: r1(host.getBoundingClientRect().height) };
  }

  const CONFIG_NAME = Object.fromEntries(CONFIGS.map(([c, n]) => [c, n]));

  /* Measures the examples the page actually shows, one row per distinct
     configuration-and-size pair. Nothing is rendered just to be measured, and
     a pair that appears in several sections is still measured once — the same
     no-duplication rule the sections follow. */
  function measure() {
    const onScale = v => SCALE.has(Math.round(v));
    const seen = new Set(), rows = [];
    document.querySelectorAll('[data-config]').forEach(host => {
      const size = (host.className.match(/\bs(\d+)\b/) || [])[1];
      const config = host.dataset.config;
      const key = config + '@' + size;
      if (!size || seen.has(key)) return;
      seen.add(key);
      rows.push({ size, config, name: CONFIG_NAME[config], m: measureConfig(host) });
    });
    rows.sort((a, b) => b.size - a.size ||
      CONFIGS.findIndex(c => c[0] === a.config) - CONFIGS.findIndex(c => c[0] === b.config));

    const yes = (v, ok) => '<td class="' + (ok ? 'ok' : 'off') + '">' + v + (ok ? ' ✓' : ' ✗') + '</td>';
    const H = T.table;
    document.getElementById('measure-table').innerHTML =
      '<tr><th>' + H.size + '</th><th>' + H.config + '</th><th>' + H.icons + '</th>' +
      '<th>' + H.gaps + '</th><th>' + H.padding + '</th><th>' + H.expected + '</th>' +
      '<th>' + H.actual + '</th><th>' + H.height + '</th></tr>' +
      rows.map(x => !x.m
        ? '<tr><th>' + metric(x.size + ' px') + '</th><td colspan="7">' + H.pending + '</td></tr>'
        : '<tr><th>' + metric(x.size + ' px') + '</th><td>' + x.name + '</td>' +
          '<td dir="ltr">' + x.m.icons + '</td>' +
          (x.m.square ? '<td>—</td><td>' + H.square + '</td>'
                      : '<td dir="ltr">' + x.m.gaps + ' × ' + x.m.gap + 'px</td>' +
                        yes(x.m.pad + 'px', onScale(x.m.pad))) +
          '<td dir="ltr">' + x.m.expected + 'px</td>' +
          yes(x.m.actual + 'px', Math.abs(x.m.actual - x.m.expected) < 0.6) +
          yes(x.m.h + 'px', x.m.h === Number(x.size)) + '</tr>').join('') +
      '<tr><td colspan="8" style="white-space:normal">' + H.footnote + '</td></tr>';
  }

  /* Nothing transitions any more, so a single frame is enough for layout to
     settle. (The old 620ms wait existed because padding animated over 550ms
     and measuring immediately reported values mid-flight.) */
  const measureWhenSettled = () => requestAnimationFrame(() => requestAnimationFrame(measure));

  const toggle = (id, cls) =>
    document.getElementById(id).addEventListener('change', e => {
      document.body.classList.toggle(cls, e.target.checked);
      measureWhenSettled();
    });
  toggle('trace', 'trace');

  /* Jelly upgrades its elements asynchronously; measure once they exist. */
  Promise.all([
    customElements.whenDefined('jelly-button'),
    customElements.whenDefined('jelly-icon-button')
  ]).then(() => {
    CONTROLS.forEach(el => setP(el, 0));
    setTimeout(measure, 300);
  });
  if (document.fonts && document.fonts.ready) document.fonts.ready.then(measure);
  measure();
